typography_spectrum: 0.13395183393731713
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.08829610398970544
  lightness: 0.8473468483425677
  saturation: 0.48904219130054116
  rhythmicContrast: 0.424732712097466
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7918335078284144
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Dennis
name: 50FIT.co
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Always FIT
description: ''
purpose: []
