title: Always FIT
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: ''
color:
  saturation: 0.4890421913005412
  brandStrength: 0.08829610398970544
  rhythmicContrast: 0.424732712097466
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  lightness: 0.8473468483425677
cta:
  bucket: null
  version: null
  domain: null
favicon: null
author:
  name: Dennis
name: 50FIT.co
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
typography_spectrum: 0.1339518339373171
layout_spectrum: 1
