typography_spectrum: 0.39537110226228833
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.5643896758556366
  lightness: 0.823034844128415
  saturation: 0.3602886132430285
  rhythmicContrast: 0.9895286282990128
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1256532638799399
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Dennis
name: 50FIT.co
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/77b4114c-95aa-4966-b41d-d1f6d6a717e3.jpg
title: Always FIT
description: ''
purpose: []
